### ISSUE TITLE
how to start ?

### ISSUE THREAD

**Issue by daslicht** [ThiefMaster/jscast#1]
How do you start the server ?

I tried : 
node simple-cli.js but I just get : 

aslicht:jscast daslicht$ node simple-cli.js jscast

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/daslicht/node/jscast/node_modules/buffertools/buffertools.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
daslicht:jscast daslicht$

**Comment by ThiefMaster** [comment]
Did you install jscast some time ago and updated node since that? If yes, `rm -rf node_modules` and run `npm install` again

**Comment by daslicht** [comment]
Ok that solved it, no more errors, thank you.
Do you have an example how to use it now, please?

**Comment by ThiefMaster** [comment]
When installing it using npm it should install a `jscast` executable.
Copy `jscast.yml`, edit the values, and pass the path to your copy as the first argument to `jscast`.

**Comment by daslicht** [comment]
I just re-cloned it and npm install:

But I dont get the executeable?:

daslicht:jscast daslicht$ ls
README.md   lib     package.json    simple-cli.js
jscast.yml  node_modules    public      templates

**Comment by ThiefMaster** [comment]
I think it's only installed if you `npm install jscast`. If you run it from a git clone simply use `node simple-cli.js` instead.

**Comment by daslicht** [comment]
I manage to start it now and connect to it with vlc.
Which source client do you use?
A Node based source client which could read cuesheets would be awesome
